### ISSUE TITLE
Framework: React for building our frontend solution

### ISSUE THREAD

**Issue by onyijne** [BuildForSDG/Phenom-Frontend#2]
**Current template cannot serve our need .**
As seen at [js-starter](https://github.com/BuildForSDG/js-starter), the base template for our frontend solution is relatively without code we could work on based on the technical requirements of our project.

**A tested and trusted framework will be solid ground to start on**
React being a modern framework for developing robust and enterprise ready frontend application is a good option based on our frontend innovator's experiences.

**Merging both templates**
The current [js-starter](https://github.com/BuildForSDG/js-starter) template has a basic standard  
which must be kept if we want good code ratings, hence ensure to add the app.properties file, and confirm the  __tests__ folder and other config files are included.

**Comment by onyijne** [comment]
please [see](https://github.com/BuildForSDG/Phenom-Frontend/issues/3#issuecomment-626240180) before you proceed.

**Comment by onyijne** [comment]
on a second thought, since `ionic start --type=react` uses typescript (file extensions are ts) by default, and in other to build on the default [js-template](https://github.com/BuildForSDG/js-starter) rather than removing it, you can first setup [parcel with react](https://blog.jakoblind.no/react-parcel/), then [add ionic](https://dev.to/ionic/adding-ionic-react-to-an-existing-react-project-4kib).

**Comment by onyijne** [comment]
@Aliyugambo @habibkayode123 @nerjib @prominded lets point out what still needs to be done for the template to be in good to go, or approve if you think it’s okay.

**Comment by onyijne** [comment]
@Aliyugambo @habibkayode123 @nerjib @prominded lets point out what still needs to be done for the template to be in good to go, or approve if you think it’s okay.

**Comment by Aliyugambo** [comment]
from my point of view i think the template is good to go

**Comment by prominded** [comment]
Hopefully we ll close all pending frontend issues by tomorrow sunday 16th may.

I think a few dependencies we need to specify in d package.json file to get us fully ready. 

I m trying to conclude d best approach to state management in React given d perculiarities of d project, after which we can tie all d pieces together.

**Comment by prominded** [comment]
@onyijne, are there still any specific concerns regarding the answers provided by @Aliyugambo?

Please lets know so we can attend to it

**Comment by onyijne** [comment]
> @onyijne, are there still any specific concerns regarding the answers provided by @Aliyugambo?
> 
> Please lets know so we can attend to it

Regarding what, I don’t understand what you’re talking about.

**Comment by Aliyugambo** [comment]
@ttl why is this issue still not close. since all have been done i mean the necessary research are all done.

**Comment by onyijne** [comment]
> @Ttl why is this issue still not close. since all have been done i mean the necessary research are all done.

[PR#7](https://github.com/BuildForSDG/Phenom-Frontend/pull/7) is still remaining one review to be merged. same as [Phenom-Backend-PR#6](https://github.com/BuildForSDG/Phenom-Backend/pull/6)
