### ISSUE TITLE
Information on Integrating a UI Framework

### ISSUE THREAD

**Issue by onyijne** [BuildForSDG/Phenom-Frontend#3]
**A need for UI framework**
Considering we the project will be serving real world users, It's is okay to integrate a UI framework that has native features.

**Ionic is just okay**
We need a brief research on using Ionic with React (current best practices should be considered). This will help guide us as we build.

**PWA will be a good alternative**
We can also use PWA if Ionic will not be applicable considering time.

**Comment by onyijne** [comment]
@Aliyugambo we need this to guide us

**Comment by Aliyugambo** [comment]
**Information on integrating UI framework**
Considering we the project will be serving real world users,  integrating a UI framework that has native features is the bast.
Ionic Framework is an open source UI toolkit for building performance, high-quality mobile and desktop apps using web technologies — HTML, CSS, and JavaScript — with integrations for popular frameworks like React.
The documentation on how to integrate ionic with React can be found at
 **https://ionicframework.com/**docs also the github page can be found at **https://github.com/ionic-team/ionic-site**
Alternatively
PWA (progressive web Apps ) documentation all required information can be found at
**https://ionicframework.com/docs/react/pwa** 
all the required information about how we are to integrate ionic framework with react in our project can be found at the links provided above thanks

**Comment by onyijne** [comment]
Okay thanks, so since using Ionic with React exposes the same tooling, we will `ionic start --type=react --capacitor` for [issue#2](https://github.com/BuildForSDG/Phenom-Frontend/issues/2)
we will be using [capacitor](https://capacitor.ionicframework.com/) for android native build and PWA.  

@aliyugambo please help us with [issue#5](https://github.com/BuildForSDG/Phenom-Frontend/issues/5) so we start documentation as we start main coding for frontend.
