### ISSUE TITLE
Documentation tool

### ISSUE THREAD

**Issue by onyijne** [BuildForSDG/Phenom-Frontend#5]
**We should document as we code**
A brief research on tool(s) we can use for documenting our frontend code (any framework specific tool is preferred)

**What we need**
Any documentation tool that can serve in frontend development will do, however if you come across a framework specific documentation tool for React it would be more preferred.

**Comment by Aliyugambo** [comment]
Hello guys,
As based on my task.
see through the attached document

[my research.docx](https://github.com/BuildForSDG/Phenom-Frontend/files/4605760/my.research.docx)

**Comment by onyijne** [comment]
@nerjib @prominded lets work with @Aliyugambo to close out on this

**Comment by onyijne** [comment]
@nerjib @prominded lets work with @Aliyugambo to close out on this

**Comment by Aliyugambo** [comment]
hello sir, regarding the documentation tools i have compile some of the
best free documentation tools together which when use check the commit
made  be me you will see an attered doc with the required information

**Comment by onyijne** [comment]
Yes, was calling on the attention of other innovators to review your picks.

**Comment by prominded** [comment]
@Aliyugambo  and I have chosen github/github pages as documentation tool since by default github projects/repositories comes with a README.md file which is used by the github documentation Api.

Phenom frontend developers are advised to learn/used markdown text in editing the readme.md file during coding

**Comment by onyijne** [comment]
> @Aliyugambo and I have chosen github/github pages as documentation tool since by default github projects/repositories comes with a README.md file which is used by the github documentation Api.
> 
> Phenom frontend developers are advised to learn/used markdown text in editing the readme.md file during coding

Okay so we use GitHub pages.
